### PR TITLE
upgrade docker compose to 2.x

### PR DESCRIPTION
**Pull request by FoghostCn**
resolve https://github.com/apache/dubbo/issues/13775

Improve stability of integration tests

### CODE REVIEW

**Comment by FoghostCn** [comment]
@AlbumenJ PTAL,we need to change ci configuration to make it work

**Comment by AlbumenJ** [comment]
> @AlbumenJ PTAL,we need to change ci configuration to make it work

Change what?

**Comment by FoghostCn** [comment]
> > @AlbumenJ PTAL,we need to change ci configuration to make it work
> 
> Change what?

docker compose to v2.x

**Comment by AlbumenJ** [comment]
Please also update in https://github.com/apache/dubbo-integration-cases

**Comment by FoghostCn** [comment]
> Please also update in https://github.com/apache/dubbo-integration-cases

OK

**Pull request merged**
