### PR TITLE
add javax support when use jdk11

### PR DESCRIPTION
**Pull request by Huangxuny1**
See [DubboIssue#5793](https://github.com/apache/dubbo/issues/5793)

use jdk11 

Becase  `[AbstractConfig.addIntoConfigManager()](https://github.com/apache/dubbo/blob/12d99d686f3b7946758a02554f81f562fc394419/dubbo-common/src/main/java/org/apache/dubbo/config/AbstractConfig.java#L577)`  has  `@PostConstruct` annotation but Jdk11 removed JavaEE 

So when use Jdk11 to run sample , it will throw exception:
```
Exception in thread "main" java.lang.IllegalStateException: No application config found or it's not a valid config! Please add <dubbo:application name="..." /> to your spring config.
	at org.apache.dubbo.config.utils.ConfigValidationUtils.validateApplicationConfig(ConfigValidationUtils.java:371)
	at org.apache.dubbo.config.bootstrap.DubboBootstrap.checkGlobalConfigs(DubboBootstrap.java:529)
	at org.apache.dubbo.config.bootstrap.DubboBootstrap.initialize(DubboBootstrap.java:514)
	at org.apache.dubbo.config.bootstrap.DubboBootstrap.start(DubboBootstrap.java:698)
	at org.apache.dubbo.config.spring.context.DubboBootstrapApplicationListener.onContextRefreshedEvent(DubboBootstrapApplicationListener.java:52)
	at org.apache.dubbo.config.spring.context.DubboBootstrapApplicationListener.onApplicationContextEvent(DubboBootstrapApplicationListener.java:45)
	at org.apache.dubbo.config.spring.context.OneTimeExecutionApplicationContextEventListener.onApplicationEvent(OneTimeExecutionApplicationContextEventListener.java:40)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:393)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:347)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:883)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:546)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:139)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:83)
```

add profile

```
<profile>
            <id>javax.annotation</id>
            <activation>
                <jdk>[1.11,)</jdk>
            </activation>
            <dependencies>
                <dependency>
                    <groupId>javax.annotation</groupId>
                    <artifactId>javax.annotation-api</artifactId>
                    <version>1.3.2</version>
                </dependency>
            </dependencies>
</profile>
```

It will activation dependency when use jdk 11

### CODE REVIEW

**Comment by chickenlj** [comment]
Temporarily, we can have this dependency for this sample to work. I think fundamentally we need to find a way to replace PostConstruct.

**Comment by htynkn** [comment]
I agree to fix samples via adding jdk11. we can remove them once it `PostConstruct` way changed in dubbo

**Comment by htynkn** [comment]
Github CI fail because 2.7.6-SNAPSHOT is no longer available after 2.7.6 official released

**Comment by Huangxuny1** [comment]
> Github CI fail because 2.7.6-SNAPSHOT is no longer available after 2.7.6 official released which can be fixed via #159

I have merge #159 ,  PTAL

**Comment by htynkn** [comment]
@Huangxuny1 

please check travis logs, I think some projects still missing this library.
+ dubbo-samples-docker
+ dubbo-samples-ssl-provider
+ ..

If you are busy with other stuff, I'm happy to accept this PR and follow rest of projects

**Comment by Huangxuny1** [comment]
@htynkn 

OK, I'm glad you can accept the pr . I'm afraid I'll make mistakes . 

thanks,

**Pull request merged**
