### PR TITLE
refactor dubbo-samples-merge

### PR DESCRIPTION
**Pull request by dengWuuu**

### CODE REVIEW

**Comment by chickenlj** [comment]
Missing https://github.com/apache/dubbo-samples/blob/master/2-advanced/dubbo-samples-echo/case-versions.conf

**Comment by dengWuuu** [comment]
> Missing https://github.com/apache/dubbo-samples/blob/master/2-advanced/dubbo-samples-echo/case-versions.conf

actually i have the case-versions.conf in my projext

**Comment by chickenlj** [comment]
> > Missing https://github.com/apache/dubbo-samples/blob/master/2-advanced/dubbo-samples-echo/case-versions.conf
> 
> actually i have the case-versions.conf in my projext

Yeah, please ignore it. I thought it was missing since it doesn't appear in the change list.

**Review by chickenlj — APPROVED** [review]
LGTM.

**Pull request merged**
