### PR TITLE
update: multi-registry

### PR DESCRIPTION
**Pull request by Rawven**
update jdk17 && springboot3,replace spring+xml by annotation + yaml ,I have tested it locally

### CODE REVIEW

**Comment by Rawven** [comment]
Sir, I found that other modules such as the annotation module have version problems that prevent the check from passing. Can I fix it? Do I need to submit it under this PR or open a new PR?   @chickenlj

**Comment by chickenlj** [comment]
> Sir, I found that other modules such as the annotation module have version problems that prevent the check from passing. I can fix some of them. @chickenlj

Yes, the base branch has test failures. Please go ahead if you can figure out the issues, we appreciate that.

**Comment by Rawven** [comment]
Because the local environment is different from the test environment, it took me a lot of time and commits to locate the problem, but I feel that this time it should have been perfected

**Review by chickenlj — APPROVED** [review]
LGTM.

**Pull request merged**
