### PR TITLE
Add Prometheus Metrics Sample

### PR DESCRIPTION
**Pull request by songxiaosheng**

### CODE REVIEW

**Review by AlbumenJ — APPROVED** [review]
LGTM

**Comment by songxiaosheng** [comment]
> image

ok

**Comment by songxiaosheng** [comment]
artifactId bug fix

**Comment by songxiaosheng** [comment]
add test

**Review by AlbumenJ — CHANGES_REQUESTED** [review]
image

Please fix license

**Comment by songxiaosheng** [comment]
> image
> 
> Integration test failed

image
fixed

**Comment by AlbumenJ** [comment]
https://github.com/apache/dubbo-samples/actions/runs/3874769471

image

**Pull request closed without merging**
