### PR TITLE
Add rest jaxrs abnormal sample cases

### PR DESCRIPTION
**Pull request by fanlobu**
to add dubbo-samples-rest-jaxrs some abnormal sample cases

### CODE REVIEW

**Comment by AlbumenJ** [comment]
Why test failed

**Comment by fanlobu** [comment]
> Uploading image.png…
Why test failed

These examples are intended to show some common error examples in the use of rest jaxrs, so they will cause some exceptions during execution, and then the test will fail. But this cannot pass the CICD test. 
I don’t have a good way to solve it yet. Are these use cases perhaps unnecessary?

**Comment by oxsean** [comment]
@fanlobu @AlbumenJ fixed in commit:
https://github.com/apache/dubbo/pull/14334/commits/b678dda8d4ebd9cff4598db814045839e4e4cf91
wrong applyCustomizeException in non-grpc causes http status error

**Comment by oxsean** [comment]
LGTM.

**Pull request merged**
