### PR TITLE
Upgrade autowire samples

### PR DESCRIPTION
**Pull request by kkkjsh**
Modify 2-advanced/dubbo-sample-autowire org.slf4j.Logger to org.apache.dubbo.common.logger.
upgrade 2-advanced/dubbo-sample-autowire zookeeper startup method
upgrade 2-advanced/dubbo-sample-autowire to jdk17 and spring3.2.3

### CODE REVIEW

**Review by chickenlj — APPROVED** [review]
LGTM.

**Comment by chickenlj** [comment]
duplicate of #1077

**Comment by kkkjsh** [comment]
I have resolved the conflicts in 4 files and clicked Mark as resolved.

**Comment by chickenlj** [comment]
> I have resolved the conflicts in 4 files and clicked Mark as resolved.

There are still conflicts. I think maybe the easiest way is to open a new pr based on the latest codebase.

**Pull request closed without merging**
