### PR TITLE
Add 3.0 Kubernetes demos

### PR DESCRIPTION
**Pull request by AlbumenJ**

### CODE REVIEW

**Comment by htynkn** [comment]
where is dubbo-registry-kubernetes:3.0.0-SNAPSHOT?
is this samples only for 3.x Dubbo?

**Comment by AlbumenJ** [comment]
> where is dubbo-registry-kubernetes:3.0.0-SNAPSHOT?
> is this samples only for 3.x Dubbo?

hi htynkn, related source codes are in apache/dubbo@8315042be517243ee72941f771fd219c6ffc9c19

**Comment by htynkn** [comment]
> > where is dubbo-registry-kubernetes:3.0.0-SNAPSHOT?
> > is this samples only for 3.x Dubbo?
> 
> hi htynkn, related source codes are in [apache/dubbo@8315042](https://github.com/apache/dubbo/commit/8315042be517243ee72941f771fd219c6ffc9c19)

so the issue is this one is released in repo so CI can't pass

**Comment by AlbumenJ** [comment]
> > > where is dubbo-registry-kubernetes:3.0.0-SNAPSHOT?
> > > is this samples only for 3.x Dubbo?
> > 
> > 
> > hi htynkn, related source codes are in [apache/dubbo@8315042](https://github.com/apache/dubbo/commit/8315042be517243ee72941f771fd219c6ffc9c19)
> 
> so the issue is this one is not released in repo so CI can't pass

This pr is the example usage of [Dubbo support Kubernetes Native Service](https://github.com/apache/dubbo/issues/6196), but now the source code hasn't been merge to main 3.0 branch in apache/dubbo. CI can't pass because snapshot version with kubernetes support hasn't been deployed.

**Comment by htynkn** [comment]
> > > > where is dubbo-registry-kubernetes:3.0.0-SNAPSHOT?
> > > > is this samples only for 3.x Dubbo?
> > > 
> > > 
> > > hi htynkn, related source codes are in [apache/dubbo@8315042](https://github.com/apache/dubbo/commit/8315042be517243ee72941f771fd219c6ffc9c19)
> > 
> > 
> > so the issue is this one is not released in repo so CI can't pass
> 
> This pr is the example usage of [Dubbo support Kubernetes Native Service](https://github.com/apache/dubbo/issues/6196), but now the source code hasn't been merge to main 3.0 branch in apache/dubbo. CI can't pass because snapshot version with kubernetes support hasn't been deployed.

ok, I understand. so we just keep this PR pending and waiting 3.0 is released?

**Comment by AlbumenJ** [comment]
> > > > > where is dubbo-registry-kubernetes:3.0.0-SNAPSHOT?
> > > > > is this samples only for 3.x Dubbo?
> > > > 
> > > > 
> > > > hi htynkn, related source codes are in [apache/dubbo@8315042](https://github.com/apache/dubbo/commit/8315042be517243ee72941f771fd219c6ffc9c19)
> > > 
> > > 
> > > so the issue is this one is not released in repo so CI can't pass
> > 
> > 
> > This pr is the example usage of [Dubbo support Kubernetes Native Service](https://github.com/apache/dubbo/issues/6196), but now the source code hasn't been merge to main 3.0 branch in apache/dubbo. CI can't pass because snapshot version with kubernetes support hasn't been deployed.
> 
> ok, I understand. so we just keep this PR pending and waiting 3.0 is released?

ok

**Pull request closed without merging**
