### PR TITLE
Add dubbo-samples-rest module IT support

### PR DESCRIPTION
**Pull request by AlbumenJ**

### CODE REVIEW

**Comment by AlbumenJ** [comment]
image

**Review by kylixs — COMMENTED** [review]
pom.xml 的dependencyManagement有些冗余配置，删除掉dubbo、dubbo-rpc-rest、curator等依赖，保留dubbo-bom和dubbo-dependencies-zookeeper。 
参考 https://github.com/apache/dubbo-samples/pull/192

**Comment by AlbumenJ** [comment]
> pom.xml 的dependencyManagement有些冗余配置，删除掉dubbo、dubbo-rpc-rest、curator等依赖，保留dubbo-bom和dubbo-dependencies-zookeeper。
> 参考 #192

Fixed

**Review by kylixs — COMMENTED** [review]
可以用dubbo-dependencies-zookeeper 替代 curator-framework和zookeeper，参考https://github.com/apache/dubbo-samples/blob/fd47f3c3dfc4004e26b88fc3c3dd427a6822eda1/dubbo-samples-docker/pom.xml

**Comment by AlbumenJ** [comment]
> 可以用dubbo-dependencies-zookeeper 替代 curator-framework和zookeeper，参考https://github.com/apache/dubbo-samples/blob/fd47f3c3dfc4004e26b88fc3c3dd427a6822eda1/dubbo-samples-docker/pom.xml

Done

**Review by kylixs — APPROVED** [review]
It's a good job!

**Pull request merged**
