### PR TITLE
Feat/curator5 zookeeper transporter remove

### PR DESCRIPTION
**Pull request by Stellar1999**
refer: [#14028](https://github.com/apache/dubbo/pull/14028)
This is a part of PR **feat:Remove zk3.4 support in 3.3**

### CODE REVIEW

**Comment by AlbumenJ** [comment]
But how can we test on 3.3.x in the future?

**Comment by Stellar1999** [comment]
> But how can we test on 3.3.x in the future?

I think I can copy this test and fixed it for these version after 3.3.x?

**Comment by AlbumenJ** [comment]
> > But how can we test on 3.3.x in the future?
> 
> I think I can copy this test and fixed it for these version after 3.3.x?

Please go ahead. I will merge this PR after that new PR being merged.

**Comment by Stellar1999** [comment]
> > > But how can we test on 3.3.x in the future?
> > 
> > 
> > I think I can copy this test and fixed it for these version after 3.3.x?
> 
> Please go ahead. I will merge this PR after that new PR being merged.

PTAL. I copy it at integration project.

**Pull request merged**
