### PR TITLE
refactor dubbo-samples-cache

### PR DESCRIPTION
**Pull request by dengWuuu**
spring style -> spring-boot style

### CODE REVIEW

**Comment by chickenlj** [comment]
Please add ASF license for the following files:

```
ERROR the following files don't have a valid license header: 
2-advanced/dubbo-samples-cache/dubbo-samples-cache-consumer/src/main/java/org/apache/dubbo/samples/cache/Task.java 
ERROR one or more files does not have a valid license header 
Error: Process completed with exit code 1.
```

**Comment by dengWuuu** [comment]
> 

done

**Comment by dengWuuu** [comment]
> Please add ASF license for the following files:
> 
> ```
> ERROR the following files don't have a valid license header: 
> 2-advanced/dubbo-samples-cache/dubbo-samples-cache-consumer/src/main/java/org/apache/dubbo/samples/cache/Task.java 
> ERROR one or more files does not have a valid license header 
> Error: Process completed with exit code 1.
> ```

done

**Comment by chickenlj** [comment]
```java
15:18:37.404 [ZooKeeper Server Starter] INFO org.apache.zookeeper.server.ZooKeeperServerMain - Starting server
Exception in thread "ZooKeeper Server Starter" java.lang.NoClassDefFoundError: com/codahale/metrics/Reservoir
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at org.apache.zookeeper.server.metric.AvgMinMaxPercentileCounter.<init>(AvgMinMaxPercentileCounter.java:105)
	at org.apache.zookeeper.metrics.impl.DefaultMetricsProvider$DefaultMetricsContext.lambda$getSummary$2(DefaultMetricsProvider.java:126)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
	at org.apache.zookeeper.metrics.impl.DefaultMetricsProvider$DefaultMetricsContext.getSummary(DefaultMetricsProvider.java:122)
	at org.apache.zookeeper.server.ServerMetrics.<init>(ServerMetrics.java:74)
	at org.apache.zookeeper.server.ServerMetrics.<clinit>(ServerMetrics.java:44)
	at org.apache.zookeeper.server.ZooKeeperServerMain.runFromConfig(ZooKeeperServerMain.java:133)
	at org.apache.dubbo.samples.cache.EmbeddedZooKeeper$ServerRunnable.run(EmbeddedZooKeeper.java:242)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: com.codahale.metrics.Reservoir
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 21 more
```

**Comment by chickenlj** [comment]
lack of dependency

**Review by chickenlj — APPROVED** [review]
LGTM.

**Pull request merged**
